# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: post
    weight: 20
  - name: Our Research
    url: project
    weight: 30
    identifier: "us"
  - name: People
    url: people
    parent: "us"
    identifier: "people"
  - name: Publications
    url: publication
    parent: "us"
    identifier: "publications"
  - name: Events
    url: event
    parent: "us"
    identifier: "events"   
  - name: Projects
    url: project
    parent: "us"
    identifier: "projects"
    weight: 1
  - name:  Twitter
    pre: <i class='fab fa-twitter'></i> 
    url: https://twitter.com/UTS_CREDS
    weight: 70
  - name:  UTS Home
    pre: <i class='fa fa-home'></i>
    url: contact
    weight: 80
    
#####################################
 # - name: Projects
 #    url: project
 #    weight: 30    
 #  - name: Events
 #    url: event
 #    weight: 50
 #     - name: People
 #    url: people
 #    weight: 40
 #  - name: Publications
 #    url: publication
 #    weight: 60
 #    
 #  - name: project
 #    parent: "us"
 #    identifier: "proj"
 #    url: projects
 # 